### PR TITLE
Fix #38

### LINKED ISSUE #38: Simple formatter broken with non-array value extra array key in PHP > 8
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.15.1

#### Summary

Simple formatter broken with non-array value extra array key when using  PHP version 8++.

#### How to reproduce

```php
        $date   = new DateTime('2012-08-28T18:15:00Z');
        $fields = [
            'timestamp'    => $date,
            'message'      => 'foo',
            'priority'     => 42,
            'priorityName' => 'bar',
            'extra'        => null,
        ];
        $formatter = new Simple();
        echo $formatter->format($fields);
        // Throws error: TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given

        $date   = new DateTime('2012-08-28T18:15:00Z');
        $fields = [
            'timestamp'    => $date,
            'message'      => 'foo',
            'priority'     => 42,
            'priorityName' => 'bar',
            'extra'        => '',
        ];
        $formatter = new Simple();

        echo $formatter->format($fields);
        // Throws error: TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given
```

#### Expected behavior

```php
        $date   = new DateTime('2012-08-28T18:15:00Z');
        $fields = [
            'timestamp'    => $date,
            'message'      => 'foo',
            'priority'     => 42,
            'priorityName' => 'bar',
            'extra'        => null,
        ];
        $formatter = new Simple();
        echo $formatter->format($fields);
        // Output: 2012-08-28T18:15:00+00:00 bar (42): foo

        $date   = new DateTime('2012-08-28T18:15:00Z');
        $fields = [
            'timestamp'    => $date,
            'message'      => 'foo',
            'priority'     => 42,
            'priorityName' => 'bar',
            'extra'        => '',
        ];

        $formatter = new Simple();
        echo $formatter->format($fields);
        // Output: 2012-08-28T18:15:00+00:00 bar (42): foo
```

### PR DESCRIPTION
**Pull request by misterabdul**

### CODE REVIEW

**Comment by Ocramius** [comment]
@misterabdul was this supposed to be closed?

**Comment by froschdesign** [comment]
@Ocramius 
Auto-close: https://github.com/laminas/laminas-log/blob/2.16.x/.github/workflows/auto-close.yml

**Comment by Ocramius** [comment]
Reopening, since this is a bugfix

**Comment by Ocramius** [comment]
No, in this case, the author deleted their fork.

**Comment by Ocramius** [comment]
Manually merged via 178b850d8b4a480e4a9e61a2ae849e8511c17d49, thanks @misterabdul!

**Pull request closed without merging**
