### PR TITLE
Adds missing installation page to the documentation

### PR DESCRIPTION
**Pull request by froschdesign**

### CODE REVIEW

**Comment by Ocramius** [comment]
> `Continuous Integration / QA Checks (No checks,`

This is worth waiting for a bit: @internalsystemerror may have found the root cause of this problem.

Ref: https://github.com/laminas/laminas-ci-matrix-action/blob/8f0274ddf4dda6e85101b7f4eb1fef0109a12ab9/src/main.ts#L14-L22
Ref: https://laminas.slack.com/archives/C4R13GTRD/p1671466766626429?thread_ts=1671465720.814739&cid=C4R13GTRD

**Comment by Ocramius** [comment]
Retrying after https://github.com/laminas/laminas-ci-matrix-action/pull/167 :)

**Comment by internalsystemerror** [comment]
1.22.1 released, try again. And was @Xerkus you can thank

**Comment by Ocramius** [comment]
Seems like it worked: correctly picked up documentation linting + MkDocs linting, which is what was touched here by @froschdesign :+1:

**Review by Ocramius — APPROVED** [review]
Thanks @froschdesign! 

Note: trailing spaces errors are due to `README.md`: unrelated :)

**Pull request merged**
