### PR TITLE
Update to support PHP 8.3

### PR DESCRIPTION
**Pull request by nusphere**
This commit updates several dependencies in the composer.lock. Key updates include removing 'container-interop/container-interop', and upgrading 'laminas/laminas-servicemanager', 'laminas/laminas-stdlib' and 'doctrine/instantiator' among others. These upgrades ensure better compatibility and performance with newer versions of PHP.

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

This PR allow to install this package with PHP 8.3. Since the there is a dev requirement to `laminas/laminas-db` - the PR laminas/laminas-db#293 is required

### CODE REVIEW

**Comment by nusphere** [comment]
@weierophinney - I don't know why the errors in the codestyle check fail, I haven't adjusted anything else.

I only had to adapt the tests because the corresponding test trait was adapted through the PHPUnit 10 integration in the ServiceManager.

https://github.com/laminas/laminas-servicemanager/blob/3.21.x/src/Test/CommonPluginManagerTrait.php#L105C59-L105C59

This resulted in a drop of PHP 8.0 for me - which is now obsolete anyway

**Comment by froschdesign** [comment]
Blocked by: https://github.com/laminas/laminas-db/pull/293

**Comment by weierophinney** [comment]
> I don't know why the errors in the codestyle check fail, I haven't adjusted anything else.

It's because you ran a `composer update`, and it picked up a version of laminas-servicemanager that now no longer _replaces_ container-interop.

Do the following:
- Update the laminas-servicemanager dependency to `^3.12`
- Update all the factories to typehint against `Psr\Container\ContainerInterface` instead of `Interop\Container\ContainerInterface`, 

These should be done anyways, and doing it during a PHP minor bump is a great time to do it.

**Comment by nusphere** [comment]
@weierophinney The fact that I have already raised the service manager to ^3.21 obviously explains the error.

I now have all pipes clean, except for the fact that laminas-db still needs a release.

**Comment by froschdesign** [comment]
@weierophinney 
Do we really need a new release of laminas-db here? laminas-validator works also for PHP 8.3 without a new release of laminas-db. See: https://github.com/laminas/laminas-validator/pull/205
Or have I overlooked something?

**Comment by steffendietz** [comment]
@froschdesign 
The latest release of `laminas/laminas-db` does not support PHP `8.3`. So I would assume a release supporting PHP `8.3` is needed.

The reason https://github.com/laminas/laminas-validator/pull/205 went through is probably this change here:
https://github.com/laminas/laminas-validator/blob/13d1e27e474b48365c54aa370a02b17a7891b766/.laminas-ci.json#L3

**Comment by froschdesign** [comment]
@steffendietz 
Then add or update this also here.

**Review by Ocramius — APPROVED** [review]
LGTM, thanks @nusphere!

**Pull request merged**
